version: '3'
services:

  post_db:
    image: "mongo:${mongodb_version:-3.2}"
    volumes:
      - post_db:/data/db
    networks:
      back_net:
          aliases:
            - comment_db
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  ui:
    image: "${USERNAME}/ui:${ui_version:-1.0}"
    ports:
      - "${ui_exposed_web:-9292}:9292/tcp"
    networks:
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  post:
    image: "${USERNAME}/post:${post_version:-1.0}"
    networks:
      - front_net
      - back_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  comment:
    image: "${USERNAME}/comment:${comment_version:-1.0}"
    networks:
      - front_net
      - back_net
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

volumes:
  post_db:

networks:
  front_net:
  back_net:
