{
 "title": "UI_Service_Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "HTTP requests rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(ui_request_count[1m])" }
   ]
  },
  {
   "title": "Error rate",
   "type": "graph",
   "description": "test change",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{http_status=~\"^[45].*\"}[1m])"
    }
   ]
  },
  {
   "title": "HTTP response time 95th percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ]
  }
 ]
}