version: '3.3'
services:
  post_db:
    image: "mongo:${mongodb_version:-3.2}"
    volumes:
      - post_db:/data/db
    networks:
      back_net:
          aliases:
            - comment_db
            - post_db
  ui:
    build: ./ui
    image: "${USERNAME}/ui:${ui_version:-1.0}"
    ports:
      - "${ui_exposed_web:-9292}:9292/tcp"
    networks:
      - front_net
  post:
    build: ./post-py
    image: "${USERNAME}/post:${post_version:-1.0}"
    networks:
      - back_net
      - front_net
  comment:
    build: ./comment
    image: "${USERNAME}/comment:${comment_version:-1.0}"
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  front_net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
  back_net:
    ipam:
      config:
        - subnet: 10.0.2.0/24
